name: Build and Test
run-name: Build and Test
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev"
      - "add-cypress"
  pull_request:
    branches:
      - "main"
      - "dev"
    paths:
      - ".github/workflows/build.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install elan and build server
        uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "Projects/mathlib-demo"
          use-github-cache: false
          build: true
          test: false
          lint: false

      - name: Install dependencies
        run: npm ci

      - name: Build client for production
        run: npm run build:client

      - name: Run Cypress tests
        run: npm test

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
